version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: GestionReclamation
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: 
      context: ./backend_GeRe
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/GestionReclamation?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
    ports:
      - "9090:9090"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontendGeRe
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: